<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\VitalGest.Core\VitalGest.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.0.0" />
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
    <PackageReference Include="FluentValidation" Version="11.11.0" />
    <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.11.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.10" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.21.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="DependencyInjection\" />
    <Folder Include="DTOs\Audit\" />
    <Folder Include="DTOs\Dashboard\" />
    <Folder Include="DTOs\Documents\" />
    <Folder Include="DTOs\Employees\" />
    <Folder Include="DTOs\Insurance\" />
    <Folder Include="DTOs\Notifications\" />
    <Folder Include="DTOs\Reports\" />
    <Folder Include="DTOs\Search\" />
    <Folder Include="Mappings\" />
    <Folder Include="Validators\" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
